name: GreenWave
description: "this app help for nature"


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  icons_launcher: ^3.0.0
  flutter_native_splash: ^2.4.1
  connectivity_plus: ^6.0.5
  lottie: ^3.1.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  delayed_widget: ^1.1.2
  path_provider: ^2.1.5
  dio: ^5.7.0
  animations: ^2.0.11
  gap: ^3.0.1
  font_awesome_flutter: any
  get_storage: ^2.1.1
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/Core/Gen

flutter:

  uses-material-design: true
  assets:
    - assets/png/
    - assets/json/
    - assets/jpg/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


icons_launcher:
  image_path: 'assets/png/logowb.png'
  platforms:
    android:
      enable: true
      adaptive_round_image: 'assets/png/logowb.png'
    ios:
      enable: true
      image_path: 'assets/png/logowb.png'
    web:
      enable: true
      image_path: 'assets/png/logowb.png'